
DWAPlannerROS:
  acc_lim_theta: 3.14   #On ROS documentation it's acc_lim_theta, actually this is what we use.
  acc_lim_x: 0.5
  max_vel_trans: 10.0
  max_vel_trans: 0.0

  max_vel_x: 3.0
  min_vel_x: 0.0

  # Differential-drive robot configuration
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0

#  max_rot_vel: 1.1
#  min_rot_vel: 0.0
#
#  yaw_goal_tolerance: 0.38      #Might increase this depending on need.
#  xy_goal_tolerance: 0.15
#
  sim_granularity: 0.025
  sim_time: 3.5
  vx_samples: 40
  vy_samples: 0
  vth_samples: 80
#
#  path_distance_bias: 64 #0.8
#  goal_distance_bias: 24 #1.5
#  occdist_scale: 0.01 #0.025
#
#  forward_point_distance: 0.1 #0.325 #The distance from the center point of the robot to place an additional scoring point, in meters
#
#  stop_time_buffer: 0.05   #The amount of time that the robot must stop before a collision in order for a trajectory to be considered valid in seconds
#  scaling_speed: 0.25     #The absolute value of the velocity at which to start scaling the robot's footprint, in m/s
#  max_scaling_factor: 0.2 #The maximum factor to scale the robot's footprint by
#
#  publish_cost_grid: false # When true, a sensor_msgs/PointCloud2 will be available on the ~<name>/cost_cloud topic. Each point cloud represents the
#  #cost grid and has a field for each individual scoring function component as well as the overall cost for each cell, taking the scoring parameters into account.
#
#  oscillation_reset_dist: 0.45



