// Generated by gencpp from file nuturtle_robot/StartRequest.msg
// DO NOT EDIT!


#ifndef NUTURTLE_ROBOT_MESSAGE_STARTREQUEST_H
#define NUTURTLE_ROBOT_MESSAGE_STARTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nuturtle_robot
{
template <class ContainerAllocator>
struct StartRequest_
{
  typedef StartRequest_<ContainerAllocator> Type;

  StartRequest_()
    : ccw_or_forward(false)  {
    }
  StartRequest_(const ContainerAllocator& _alloc)
    : ccw_or_forward(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ccw_or_forward_type;
  _ccw_or_forward_type ccw_or_forward;





  typedef boost::shared_ptr< ::nuturtle_robot::StartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nuturtle_robot::StartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartRequest_

typedef ::nuturtle_robot::StartRequest_<std::allocator<void> > StartRequest;

typedef boost::shared_ptr< ::nuturtle_robot::StartRequest > StartRequestPtr;
typedef boost::shared_ptr< ::nuturtle_robot::StartRequest const> StartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nuturtle_robot::StartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nuturtle_robot::StartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nuturtle_robot::StartRequest_<ContainerAllocator1> & lhs, const ::nuturtle_robot::StartRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ccw_or_forward == rhs.ccw_or_forward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nuturtle_robot::StartRequest_<ContainerAllocator1> & lhs, const ::nuturtle_robot::StartRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nuturtle_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nuturtle_robot::StartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nuturtle_robot::StartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nuturtle_robot::StartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3cef58e896b7b1fe8be0821b7a77707";
  }

  static const char* value(const ::nuturtle_robot::StartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3cef58e896b7b1fULL;
  static const uint64_t static_value2 = 0xe8be0821b7a77707ULL;
};

template<class ContainerAllocator>
struct DataType< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nuturtle_robot/StartRequest";
  }

  static const char* value(const ::nuturtle_robot::StartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ccw_or_forward\n"
;
  }

  static const char* value(const ::nuturtle_robot::StartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ccw_or_forward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nuturtle_robot::StartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nuturtle_robot::StartRequest_<ContainerAllocator>& v)
  {
    s << indent << "ccw_or_forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ccw_or_forward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUTURTLE_ROBOT_MESSAGE_STARTREQUEST_H
