// Generated by gencpp from file nuturtle_robot/Start.msg
// DO NOT EDIT!


#ifndef NUTURTLE_ROBOT_MESSAGE_START_H
#define NUTURTLE_ROBOT_MESSAGE_START_H

#include <ros/service_traits.h>


#include <nuturtle_robot/StartRequest.h>
#include <nuturtle_robot/StartResponse.h>


namespace nuturtle_robot
{

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start
} // namespace nuturtle_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nuturtle_robot::Start > {
  static const char* value()
  {
    return "e3cef58e896b7b1fe8be0821b7a77707";
  }

  static const char* value(const ::nuturtle_robot::Start&) { return value(); }
};

template<>
struct DataType< ::nuturtle_robot::Start > {
  static const char* value()
  {
    return "nuturtle_robot/Start";
  }

  static const char* value(const ::nuturtle_robot::Start&) { return value(); }
};


// service_traits::MD5Sum< ::nuturtle_robot::StartRequest> should match
// service_traits::MD5Sum< ::nuturtle_robot::Start >
template<>
struct MD5Sum< ::nuturtle_robot::StartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nuturtle_robot::Start >::value();
  }
  static const char* value(const ::nuturtle_robot::StartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nuturtle_robot::StartRequest> should match
// service_traits::DataType< ::nuturtle_robot::Start >
template<>
struct DataType< ::nuturtle_robot::StartRequest>
{
  static const char* value()
  {
    return DataType< ::nuturtle_robot::Start >::value();
  }
  static const char* value(const ::nuturtle_robot::StartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nuturtle_robot::StartResponse> should match
// service_traits::MD5Sum< ::nuturtle_robot::Start >
template<>
struct MD5Sum< ::nuturtle_robot::StartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nuturtle_robot::Start >::value();
  }
  static const char* value(const ::nuturtle_robot::StartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nuturtle_robot::StartResponse> should match
// service_traits::DataType< ::nuturtle_robot::Start >
template<>
struct DataType< ::nuturtle_robot::StartResponse>
{
  static const char* value()
  {
    return DataType< ::nuturtle_robot::Start >::value();
  }
  static const char* value(const ::nuturtle_robot::StartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NUTURTLE_ROBOT_MESSAGE_START_H
