#!/usr/bin/env python

import rospy
from utils import *
# from nuturtlebot.msg import WheelCommands
from wheel_vel_executioner import WheelVelExecutioner
from wheel_encoder_publisher import WheelEncodersPublisher
import numpy as np

if __name__=="__main__":
    rospy.init_node("cmd_vel_executioner")
    rospy.loginfo("[cmd_vel_executioner]: Initialized Successfully.")

    rate = rospy.Rate(10)
    executioner = WheelVelExecutioner()
    wheel_encoders = WheelEncodersPublisher()
    while not rospy.is_shutdown():
        # if executioner.timeOut():
        #     executioner.brakeNow()
        # left_val, right_val = wheel_encoders.get_encoder_linear_variation()
        wheel_encoders.publish_wheel_linear_vel()
        rate.sleep()

    rospy.loginfo("[cmd_vel_executioner]: Exited Successfully.")


